#!/usr/bin/python
#
# counting sort

def counting_sort(the_list, max_value):

    # array of 0s at indices 0..max_value
    nums_to_counts = [0] * (max_value+1)

    # populate nums_to_counts
    for item in the_list:
        nums_to_counts[item] += 1

    # populate the final sorted list
    sorted_list = []

    # for each item in nums_to_counts
    for item, count in enumerate(nums_to_counts):

        # for the number of times the item occurs
        for time in range(count):

            # add it to the sorted list
            sorted_list.append(item)

    return sorted_list

sorted_list = counting_sort([3, 2, 3, 1, 5], 5)
print sorted_list

