#!/usr/bin/python3

board = []

for i in range(5):
    board.append(['O'] * 5)
    
#print(board)
print(['X'] *5)

def print_board(board):
    for row in board:
        print(row)
        
#print_board(board)
